# Generated by Django 5.0.6 on 2024-06-21 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email_adress', models.EmailField(max_length=150, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('message_text', models.TextField(verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('twitter', 'X - TWITTER'), ('instagram', 'INSTAGRAM'), ('facebook', 'FACEBOOK'), ('github', 'GITHUB')], default='facebook', max_length=15, verbose_name='Rede Social')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome identificador')),
                ('url', models.URLField(unique=True, verbose_name='*URL')),
                ('active', models.BooleanField(default=False, verbose_name='*Rede Social ativa')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
    ]
