# Generated by Django 5.0.6 on 2024-06-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='type_media',
            field=models.CharField(choices=[('twitter', 'X - TWITTER'), ('instagram', 'INSTAGRAM'), ('facebook', 'FACEBOOK'), ('github', 'GITHUB'), ('linkedin', 'LINKEDIN')], default='facebook', max_length=15, verbose_name='Rede Social'),
        ),
    ]
