# Generated by Django 5.0.6 on 2024-06-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_socialmedia_type_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='name_user',
        ),
    ]
