# Generated by Django 5.0.6 on 2024-06-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='*Titulo')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Titulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='*Data de Publicação')),
                ('posted_by', models.CharField(max_length=100, verbose_name='*Autor')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo ou Sub Titulo')),
                ('content_text', models.TextField(verbose_name='*Texto da Publicação')),
                ('order', models.PositiveIntegerField(verbose_name='*Ordem do texto')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication', verbose_name='*Publicação')),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
            },
        ),
    ]
